# Generated by Django 3.0.7 on 2020-06-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200629_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ev_info',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='ev_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
